# Generated by Django 5.1.6 on 2025-08-27 20:29

import django.core.validators
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_invoice_id', models.CharField(blank=True, help_text='Unique identifier for the Stripe invoice', max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=3)),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('invoice_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('created', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_at', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_reason', models.CharField(blank=True, max_length=30, null=True)),
                ('collection_method', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Aprobado'), ('IN_PROCESS', 'En proceso'), ('INMEDIATION', 'En mediación'), ('REJECTED', 'Rechazado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('CHARGEBACK', 'Contracargo')], default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('slug', models.SlugField(blank=True, verbose_name='Tenant URL Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField()),
                ('company_email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('portal', models.SlugField(max_length=100, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('on_trial', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=11, null=True)),
                ('account_type', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('card', 'Card'), ('us_bank_account', 'US Bank Account'), ('sepa_debit', 'SEPA Debit')], max_length=20)),
                ('exp_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2050)])),
                ('stripe_payment_method_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the plan', max_length=100)),
                ('description', models.TextField(help_text='Description of the plan')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for the plan', max_digits=6)),
                ('plan_type', models.CharField(choices=[('BASIC', 'Básico'), ('PROFESSIONAL', 'Profesional'), ('ENTERPRISE', 'Empresarial')], default='BASIC', help_text='Type of plan (e.g., BASIC, PROFESSIONAL, ENTERPRISE)', max_length=20)),
                ('interval', models.CharField(blank=True, choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], default='MONTHLY', help_text='Interval for the plan (e.g., MONTHLY, ANNUAL)', max_length=20, null=True)),
                ('stripe_price_id', models.CharField(help_text='Unique identifier for the Stripe price associated with this plan', max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Unique identifier for the Stripe subscription', max_length=100, null=True, unique=True)),
                ('unit_amount', models.DecimalField(decimal_places=2, help_text='Amount charged for the subscription', max_digits=6)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incompleto'), ('INCOMPLETE_EXPIRED', 'Incompleto expirado'), ('ACTIVE', 'Aprobado'), ('TRIALING', 'Prueba'), ('PAST_DUE', 'Pago fallido'), ('CANCELED', 'Cancelado'), ('UNPAID', 'No pagado'), ('PAUSED', 'Pausado')], default='INCOMPLETE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
