# Generated by Django 5.1.6 on 2025-07-25 18:36

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField()),
                ('company_email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('portal', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('mercadopago_customer_id', models.CharField(max_length=200, unique=True)),
                ('mercadopago_user_id', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Description of the plan')),
                ('plan_type', models.CharField(choices=[('BASIC', 'Básico'), ('PROFESSIONAL', 'Profesional'), ('ENTERPRISE', 'Empresarial')], default='BASIC', help_text='Type of plan (e.g., BASIC, PROFESSIONAL, ENTERPRISE)', max_length=20)),
                ('interval', models.CharField(blank=True, choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], default='MONTHLY', help_text='Interval for the plan (e.g., MONTHLY, ANNUAL)', max_length=20, null=True)),
                ('stripe_price_id', models.CharField(help_text='Unique identifier for the Stripe price associated with this plan', max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organizations.organizationmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mercadopago_card_id', models.CharField(max_length=100, unique=True)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('first_six_digits', models.CharField(max_length=6)),
                ('issuer', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_card', to='organizations.organizationmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_approved', models.DateTimeField()),
                ('payment_type', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('IN_PROCESS', 'En proceso'), ('INMEDIATION', 'En mediación'), ('REJECTED', 'Rechazado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('CHARGEBACK', 'Contracargo')], default='APPROVED', max_length=20)),
                ('stripe_payment_id', models.CharField(help_text='Unique identifier for the Stripe payment', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_organization', to='organizations.organizationmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(help_text='Unique identifier for the Stripe subscription', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('unit_amount', models.DecimalField(decimal_places=2, help_text='Amount charged for the subscription', max_digits=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('IN_PROCESS', 'En proceso'), ('INMEDIATION', 'En mediación'), ('REJECTED', 'Rechazado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('CHARGEBACK', 'Contracargo')], default='APPROVED', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_payment', to='organizations.organizationmodel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_payment', to='organizations.pricemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
