# Generated by Django 5.1.6 on 2025-08-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainmodel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='domains', to='organizations.organizationmodel'),
        ),
        migrations.AddField(
            model_name='paymentmethodmodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='payment_methods_organization', to='organizations.organizationmodel'),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='organization_subscription', to='organizations.organizationmodel'),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='subscription_price', to='organizations.pricemodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='invoice_subscription', to='organizations.subscriptionmodel'),
        ),
    ]
