# Generated by Django 5.1.6 on 2025-04-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationmodel_administrative_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
