# Generated by Django 5.1.6 on 2025-10-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Abierto'), ('PAID', 'Pagado'), ('UNCOLLECTIBLE', 'No cobrable'), ('VOID', 'Anulado')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='PriceLimitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_locations', models.PositiveIntegerField(default=0)),
                ('max_users', models.PositiveIntegerField(default=0)),
                ('max_feedbacks', models.PositiveIntegerField(default=0)),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_limit', to='organizations.pricemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
