# Generated by Django 5.1.6 on 2025-11-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_invoicemodel_status_pricelimitmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='proration',
            field=models.BooleanField(default=False),
        ),
    ]
