# Generated by Django 5.1.6 on 2025-08-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback_system_permissions', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrouppermissionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlevelpermissionmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_level_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlocationpermissionmodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_permissions', to='locations.locationmodel'),
        ),
        migrations.AddField(
            model_name='userlocationpermissionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
